
variable "ami_base" {
  type    = string
  default = "ami-a4dc46db"
}

variable "ami_name" {
  type    = string
  default = "baseline-ubuntu-1604"
}

variable "ami_sha" {
  type    = string
  default = "${env("SHA")}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_description = "${var.ami_name} AMI"
  ami_name        = "${var.ami_name} ${local.timestamp}"
  ami_regions     = ["us-east-1"]
  instance_type   = "t1.micro"
  region          = "us-east-1"
  run_tags = {
    ami-create = "${var.ami_name}"
  }
  source_ami   = "${var.ami_base}"
  ssh_username = "ubuntu"
  tags = {
    AMI        = "${var.ami_name}"
    OS_Name    = "Ubuntu"
    OS_Version = "16.04"
    SHA        = "${var.ami_sha}"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done"]
  }

  provisioner "shell" {
    scripts = ["./base/tasks/baseline.sh", "./base/tasks/cleanup.sh", "./base/tasks/debug.sh"]
  }

  post-processor "manifest" {
    output     = "manifest-base.json"
    strip_path = true
  }
}
